# Task 4.8: Grouping Data & Aggregating Variables

### This notebook contains:
    01. Importing Libraries
    02. Importing Data
    03. Grouping Data & Aggregating Variables - Task
    04. Additional Data Cleaning (Outlier Removal)

## 01. Importing Libraries

In [3]:
# Import libraries
import pandas as pd
import numpy as np
import os

## 02. Importing Data

In [4]:
# turning project folder path into string
path = r'/Users/lisa/DA Projects/12-2022 Instacart Basket Analysis'

In [5]:
# Importing flagged and merged orders and prods data from exercise
ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'orders_products_merge.pkl'))

## 03. Grouping Data & Aggregating Variables - Task

In [6]:
# checking import
ords_prods_merge.head()

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,...,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag
0,2539329,1,1,2,8,NaN,True,196,1,0,...,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer
1,2398795,1,2,3,7,15.0,False,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Less busy,Average orders,10,New customer
2,473747,1,3,3,12,21.0,False,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Less busy,Most orders,10,New customer
3,2254736,1,4,4,7,29.0,False,196,1,1,...,77,7,9.0,both,Mid-range product,Least busy,Less busy,Average orders,10,New customer
4,431534,1,5,4,15,28.0,False,196,1,1,...,77,7,9.0,both,Mid-range product,Least busy,Less busy,Most orders,10,New customer

In [7]:
ords_prods_merge.shape

(32404859, 21)

### Question 2. 
In this Exercise, you learned how to find the aggregated mean of the “order_number” column grouped by “department_id” for a subset of your dataframe. Now, repeat this process for the entire dataframe.

In [8]:
# Calculate aggregated mean for entire df
ords_prods_merge.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.457838
2                17.277920
3                17.170395
4                17.811403
5                15.215751
6                16.439806
7                17.225802
8                15.340650
9                15.895474
10               20.197148
11               16.170638
12               15.887671
13               16.583536
14               16.773669
15               16.165037
16               17.665606
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

### Question 3. 
Analyze the result. How do the results for the entire dataframe differ from those of the subset? Include your comments in a markdown cell below the executed code.

As we used the full dataframe and not just a subset, we are now seeing the results for all departments. Additonally the prior results were skewed as they only used a small part (1000000 rows of around 32000000 rows) of the data for the calculation. We could potentially get a first overview from working with a smaller subset but as we could never be sure how accurate the results are without testing it on the whole dataframe, testing it with a subset is more useful to find out how to approach the problem/questions we want to answer while using less processing power.

### Question 4. 
Follow the instructions in the Exercise for creating a loyalty flag for existing customers using the transform() and loc() functions.

I followed along with the exercise. The loyalty flag is already in the ords_prods_merge dataframe.

### Question 5. 
The marketing team at Instacart wants to know whether there’s a difference between the spending habits of the three types of customers you identified. Use the loyalty flag you created and check the basic statistics of the product prices for each loyalty category (Loyal Customer, Regular Customer, and New Customer). What you’re trying to determine is whether the prices of products purchased by loyal customers differ from those purchased by regular or new customers.

In [9]:
# calculating basic stats for loyalty category
ords_prods_merge.groupby('loyalty_flag').agg({'prices': ['mean', 'min', 'max', 'sum']})

                     prices
                       mean  min      max          sum
loyalty_flag
Loyal customer    10.386336  1.0  99999.0  106814042.2
New customer      13.294670  1.0  99999.0   83011787.2
Regular customer  12.495717  1.0  99999.0  198391693.2

Loyal customers spend on average the least amount and new customers the most with regular customers close to that. Regular customers spend overall the most money, almost double than loyal customers.

### Question 6.
The team now wants to target different types of spenders in their marketing campaigns. This can be achieved by looking at the prices of the items people are buying. Create a spending flag for each user based on the average price across all their orders using the following criteria:

    If the mean of the prices of products purchased by a user is lower than 10, then flag them as a “Low spender.”
    If the mean of the prices of products purchased by a user is higher than or equal to 10, then flag them as a “High spender.”

In [10]:
# Splitting data in groups based on user_id and creating a new column with their average prcies
ords_prods_merge['avg_price'] = ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

In [11]:
# checking results
ords_prods_merge.head(20)

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,...,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,avg_price
0,2539329,1,1,2,8,NaN,True,196,1,0,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797
1,2398795,1,2,3,7,15.0,False,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Less busy,Average orders,10,New customer,6.367797
2,473747,1,3,3,12,21.0,False,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Less busy,Most orders,10,New customer,6.367797
3,2254736,1,4,4,7,29.0,False,196,1,1,...,7,9.0,both,Mid-range product,Least busy,Less busy,Average orders,10,New customer,6.367797
4,431534,1,5,4,15,28.0,False,196,1,1,...,7,9.0,both,Mid-range product,Least busy,Less busy,Most orders,10,New customer,6.367797
5,3367565,1,6,2,7,19.0,False,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797
6,550135,1,7,1,9,20.0,False,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Busy day,Average orders,10,New customer,6.367797
7,3108588,1,8,1,14,14.0,False,196,2,1,...,7,9.0,both,Mid-range product,Regularly busy,Busy day,Most orders,10,New customer,6.367797
8,2295261,1,9,1,16,0.0,False,196,4,1,...,7,9.0,both,Mid-range product,Regularly busy,Busy day,Most orders,10,New customer,6.367797
9,2550362,1,10,4,8,30.0,False,196,1,1,...,7,9.0,both,Mid-range product,Least busy,Less busy,Average orders,10,New customer,6.367797
10,2968173,15,15,1,9,7.0,False,196,2,0,...,7,9.0,both,Mid-range product,Regularly busy,Busy day,Average orders,22,Regular customer,3.980556
11,1870022,15,17,2,16,8.0,False,196,6,1,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,22,Regular customer,3.980556
12,1911383,15,18,2,11,7.0,False,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,22,Regular customer,3.980556
13,2715276,15,21,1,9,7.0,False,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Busy day,Average orders,22,Regular customer,3.980556
14,487368,15,22,1,10,14.0,False,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Busy day,Most orders,22,Regular customer,3.980556
15,2293453,19,2,5,14,6.0,False,196,3,0,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,9,New customer,8.372059
16,1973799,19,5,6,12,8.0,False,196,15,1,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,9,New customer,8.372059
17,532817,19,7,4,17,6.0,False,196,1,1,...,7,9.0,both,Mid-range product,Least busy,Less busy,Most orders,9,New customer,8.372059
18,1573906,21,10,3,10,6.0,False,196,2,0,...,7,9.0,both,Mid-range product,Regularly busy,Less busy,Most orders,33,Regular customer,7.012683
19,1593000,31,10,3,8,7.0,False,196,17,0,...,7,9.0,both,Mid-range product,Regularly busy,Less busy,Average orders,20,Regular customer,8.137793

In [12]:
# creating flag for low spender
ords_prods_merge.loc[ords_prods_merge['avg_price']<10, 'spending_flag']= 'Low spender'

In [13]:
# creating flag for high spender
ords_prods_merge.loc[ords_prods_merge['avg_price'] >= 10, 'spending_flag'] = 'High Spender'

In [14]:
# checking results
ords_prods_merge['spending_flag'].value_counts(dropna=False)

Low spender     31770614
High Spender      634245
Name: spending_flag, dtype: int64

In [15]:
# checking df
ords_prods_merge[['user_id', 'spending_flag', 'avg_price']].head(60)

    user_id spending_flag  avg_price
0         1   Low spender   6.367797
1         1   Low spender   6.367797
2         1   Low spender   6.367797
3         1   Low spender   6.367797
4         1   Low spender   6.367797
5         1   Low spender   6.367797
6         1   Low spender   6.367797
7         1   Low spender   6.367797
8         1   Low spender   6.367797
9         1   Low spender   6.367797
10       15   Low spender   3.980556
11       15   Low spender   3.980556
12       15   Low spender   3.980556
13       15   Low spender   3.980556
14       15   Low spender   3.980556
15       19   Low spender   8.372059
16       19   Low spender   8.372059
17       19   Low spender   8.372059
18       21   Low spender   7.012683
19       31   Low spender   8.137793
20       31   Low spender   8.137793
21       43   Low spender   7.444898
22       43   Low spender   7.444898
23       52   Low spender   6.356287
24       52   Low spender   6.356287
25       52   Low spender   6.356287
26       52   Low spender   6.356287
27       52   Low spender   6.356287
28       52   Low spender   6.356287
29       52   Low spender   6.356287
30       52   Low spender   6.356287
31       52   Low spender   6.356287
32       52   Low spender   6.356287
33       52   Low spender   6.356287
34       52   Low spender   6.356287
35       52   Low spender   6.356287
36       52   Low spender   6.356287
37       67   Low spender   7.656790
38       67   Low spender   7.656790
39       67   Low spender   7.656790
40       67   Low spender   7.656790
41       67   Low spender   7.656790
42       67   Low spender   7.656790
43       67   Low spender   7.656790
44       67   Low spender   7.656790
45       67   Low spender   7.656790
46       67   Low spender   7.656790
47       67   Low spender   7.656790
48       67   Low spender   7.656790
49       67   Low spender   7.656790
50       67   Low spender   7.656790
51       67   Low spender   7.656790
52       67   Low spender   7.656790
53       67   Low spender   7.656790
54       67   Low spender   7.656790
55       67   Low spender   7.656790
56       81   Low spender   8.165385
57       81   Low spender   8.165385
58       82   Low spender   6.441221
59       82   Low spender   6.441221

### Question 7.
In order to send relevant notifications to users within the app (for instance, asking users if they want to buy the same item again), the Instacart team wants you to determine frequent versus non-frequent customers. Create an order frequency flag that marks the regularity of a user’s ordering behavior according to the median in the “days_since_prior_order” column. The criteria for the flag should be as follows:

    If the median of “days_since_prior_order” is higher than 20, then the customer should be labeled a “Non-frequent customer.”
    If the median is higher than 10 and lower than or equal to 20, then the customer should be labeled a “Regular customer.”
    If the median is lower than or equal to 10, then the customer should be labeled a “Frequent customer.”

In [16]:
# Splitting data in groups based on user_id and creating a new column with 
# the median of their days_since_prior_order value
ords_prods_merge['order_freq'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

In [17]:
# check result
ords_prods_merge.head(60)

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,...,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,avg_price,spending_flag,order_freq
0,2539329,1,1,2,8,NaN,True,196,1,0,...,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5
1,2398795,1,2,3,7,15.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Less busy,Average orders,10,New customer,6.367797,Low spender,20.5
2,473747,1,3,3,12,21.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Less busy,Most orders,10,New customer,6.367797,Low spender,20.5
3,2254736,1,4,4,7,29.0,False,196,1,1,...,both,Mid-range product,Least busy,Less busy,Average orders,10,New customer,6.367797,Low spender,20.5
4,431534,1,5,4,15,28.0,False,196,1,1,...,both,Mid-range product,Least busy,Less busy,Most orders,10,New customer,6.367797,Low spender,20.5
5,3367565,1,6,2,7,19.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5
6,550135,1,7,1,9,20.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Busy day,Average orders,10,New customer,6.367797,Low spender,20.5
7,3108588,1,8,1,14,14.0,False,196,2,1,...,both,Mid-range product,Regularly busy,Busy day,Most orders,10,New customer,6.367797,Low spender,20.5
8,2295261,1,9,1,16,0.0,False,196,4,1,...,both,Mid-range product,Regularly busy,Busy day,Most orders,10,New customer,6.367797,Low spender,20.5
9,2550362,1,10,4,8,30.0,False,196,1,1,...,both,Mid-range product,Least busy,Less busy,Average orders,10,New customer,6.367797,Low spender,20.5
10,2968173,15,15,1,9,7.0,False,196,2,0,...,both,Mid-range product,Regularly busy,Busy day,Average orders,22,Regular customer,3.980556,Low spender,10.0
11,1870022,15,17,2,16,8.0,False,196,6,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,22,Regular customer,3.980556,Low spender,10.0
12,1911383,15,18,2,11,7.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,22,Regular customer,3.980556,Low spender,10.0
13,2715276,15,21,1,9,7.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Busy day,Average orders,22,Regular customer,3.980556,Low spender,10.0
14,487368,15,22,1,10,14.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Busy day,Most orders,22,Regular customer,3.980556,Low spender,10.0
15,2293453,19,2,5,14,6.0,False,196,3,0,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,9,New customer,8.372059,Low spender,6.0
16,1973799,19,5,6,12,8.0,False,196,15,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,9,New customer,8.372059,Low spender,6.0
17,532817,19,7,4,17,6.0,False,196,1,1,...,both,Mid-range product,Least busy,Less busy,Most orders,9,New customer,8.372059,Low spender,6.0
18,1573906,21,10,3,10,6.0,False,196,2,0,...,both,Mid-range product,Regularly busy,Less busy,Most orders,33,Regular customer,7.012683,Low spender,7.5
19,1593000,31,10,3,8,7.0,False,196,17,0,...,both,Mid-range product,Regularly busy,Less busy,Average orders,20,Regular customer,8.137793,Low spender,6.0
20,2231262,31,17,3,11,8.0,False,196,14,1,...,both,Mid-range product,Regularly busy,Less busy,Most orders,20,Regular customer,8.137793,Low spender,6.0
21,2580647,43,6,4,16,4.0,False,196,9,0,...,both,Mid-range product,Least busy,Less busy,Most orders,11,Regular customer,7.444898,Low spender,10.0
22,2187180,43,9,4,12,3.0,False,196,1,1,...,both,Mid-range product,Least busy,Less busy,Most orders,11,Regular customer,7.444898,Low spender,10.0
23,2497897,52,1,1,9,NaN,True,196,4,0,...,both,Mid-range product,Regularly busy,Busy day,Average orders,27,Regular customer,6.356287,Low spender,8.0
24,1318871,52,2,1,10,7.0,False,196,5,1,...,both,Mid-range product,Regularly busy,Busy day,Most orders,27,Regular customer,6.356287,Low spender,8.0
25,1261384,52,3,1,10,7.0,False,196,3,1,...,both,Mid-range product,Regularly busy,Busy day,Most orders,27,Regular customer,6.356287,Low spender,8.0
26,580568,52,5,2,10,8.0,False,196,6,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
27,2428073,52,7,2,7,8.0,False,196,5,1,...,both,Mid-range product,Regularly busy,Regularly busy,Average orders,27,Regular customer,6.356287,Low spender,8.0
28,342306,52,9,1,11,7.0,False,196,5,1,...,both,Mid-range product,Regularly busy,Busy day,Most orders,27,Regular customer,6.356287,Low spender,8.0
29,1520353,52,10,2,10,8.0,False,196,4,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
30,2542086,52,11,2,9,7.0,False,196,3,1,...,both,Mid-range product,Regularly busy,Regularly busy,Average orders,27,Regular customer,6.356287,Low spender,8.0
31,944694,52,12,1,16,6.0,False,196,7,1,...,both,Mid-range product,Regularly busy,Busy day,Most orders,27,Regular customer,6.356287,Low spender,8.0
32,1268191,52,15,2,11,8.0,False,196,3,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
33,1122089,52,17,2,10,6.0,False,196,4,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
34,1498922,52,18,2,10,14.0,False,196,6,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
35,180919,52,19,3,8,8.0,False,196,4,1,...,both,Mid-range product,Regularly busy,Less busy,Average orders,27,Regular customer,6.356287,Low spender,8.0
36,2695875,52,21,5,10,30.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
37,3205960,67,1,3,11,NaN,True,196,1,0,...,both,Mid-range product,Regularly busy,Less busy,Most orders,24,Regular customer,7.656790,Low spender,7.0
38,970922,67,2,1,15,5.0,False,196,2,1,...,both,Mid-range product,Regularly busy,Busy day,Most orders,24,Regular customer,7.656790,Low spender,7.0
39,596585,67,3,1,13,7.0,False,196,2,1,...,both,Mid-range product,Regularly busy,Busy day,Most orders,24,Regular customer,7.656790,Low spender,7.0
40,2037087,67,4,2,9,8.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Average orders,24,Regular customer,7.656790,Low spender,7.0
41,2474111,67,5,3,14,8.0,False,196,2,1,...,both,Mid-range product,Regularly busy,Less busy,Most orders,24,Regular customer,7.656790,Low spender,7.0
42,1568481,67,6,3,12,7.0,False,196,2,1,...,both,Mid-range product,Regularly busy,Less busy,Most orders,24,Regular customer,7.656790,Low spender,7.0
43,2048527,67,8,2,11,7.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender,7.0
44,2389031,67,9,2,14,7.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender,7.0
45,2378562,67,10,1,10,6.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Busy day,Most orders,24,Regular customer,7.656790,Low spender,7.0
46,1515698,67,11,1,11,7.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Busy day,Most orders,24,Regular customer,7.656790,Low spender,7.0
47,1928050,67,12,2,12,8.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender,7.0
48,1949274,67,13,1,10,6.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Busy day,Most orders,24,Regular customer,7.656790,Low spender,7.0
49,551869,67,14,1,9,7.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Busy day,Average orders,24,Regular customer,7.656790,Low spender,7.0
50,768572,67,16,4,10,9.0,False,196,1,1,...,both,Mid-range product,Least busy,Less busy,Most orders,24,Regular customer,7.656790,Low spender,7.0
51,150528,67,18,5,16,4.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender,7.0
52,29758,67,19,0,14,9.0,False,196,2,1,...,both,Mid-range product,Busiest day,Busy day,Most orders,24,Regular customer,7.656790,Low spender,7.0
53,1558976,67,21,1,9,5.0,False,196,2,1,...,both,Mid-range product,Regularly busy,Busy day,Average orders,24,Regular customer,7.656790,Low spender,7.0
54,863974,67,22,1,11,14.0,False,196,3,1,...,both,Mid-range product,Regularly busy,Busy day,Most orders,24,Regular customer,7.656790,Low spender,7.0
55,2308399,67,23,1,14,14.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Busy day,Most orders,24,Regular customer,7.656790,Low spender,7.0
56,2759128,81,3,1,9,14.0,False,196,2,0,...,both,Mid-range product,Regularly busy,Busy day,Average orders,7,New customer,8.165385,Low spender,30.0
57,1812985,81,5,2,20,30.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,7,New customer,8.165385,Low spender,30.0
58,1889835,82,1,3,15,NaN,True,196,6,0,...,both,Mid-range product,Regularly busy,Less busy,Most orders,19,Regular customer,6.441221,Low spender,11.5
59,499460,82,3,5,10,5.0,False,196,2,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,19,Regular customer,6.441221,Low spender,11.5

In [18]:
# creating flag for non-frequent customer
ords_prods_merge.loc[ords_prods_merge['order_freq']>20, 'frequency_flag']= 'Non-frequent customer'

In [19]:
# creating flag for regular customer
ords_prods_merge.loc[(ords_prods_merge['order_freq']>10) & (ords_prods_merge['order_freq']<=20), 'frequency_flag']= 'Regular customer'

In [20]:
# creating flag for frequent customer
ords_prods_merge.loc[ords_prods_merge['order_freq']<=10, 'frequency_flag']= 'Frequent customer'

In [21]:
# checking results
ords_prods_merge['frequency_flag'].value_counts(dropna=False)

Frequent customer        21559853
Regular customer          7208564
Non-frequent customer     3636437
NaN                             5
Name: frequency_flag, dtype: int64

In [22]:
# checking df
ords_prods_merge[['user_id', 'frequency_flag', 'order_freq']].head(60)

    user_id         frequency_flag  order_freq
0         1  Non-frequent customer        20.5
1         1  Non-frequent customer        20.5
2         1  Non-frequent customer        20.5
3         1  Non-frequent customer        20.5
4         1  Non-frequent customer        20.5
5         1  Non-frequent customer        20.5
6         1  Non-frequent customer        20.5
7         1  Non-frequent customer        20.5
8         1  Non-frequent customer        20.5
9         1  Non-frequent customer        20.5
10       15      Frequent customer        10.0
11       15      Frequent customer        10.0
12       15      Frequent customer        10.0
13       15      Frequent customer        10.0
14       15      Frequent customer        10.0
15       19      Frequent customer         6.0
16       19      Frequent customer         6.0
17       19      Frequent customer         6.0
18       21      Frequent customer         7.5
19       31      Frequent customer         6.0
20       31      Frequent customer         6.0
21       43      Frequent customer        10.0
22       43      Frequent customer        10.0
23       52      Frequent customer         8.0
24       52      Frequent customer         8.0
25       52      Frequent customer         8.0
26       52      Frequent customer         8.0
27       52      Frequent customer         8.0
28       52      Frequent customer         8.0
29       52      Frequent customer         8.0
30       52      Frequent customer         8.0
31       52      Frequent customer         8.0
32       52      Frequent customer         8.0
33       52      Frequent customer         8.0
34       52      Frequent customer         8.0
35       52      Frequent customer         8.0
36       52      Frequent customer         8.0
37       67      Frequent customer         7.0
38       67      Frequent customer         7.0
39       67      Frequent customer         7.0
40       67      Frequent customer         7.0
41       67      Frequent customer         7.0
42       67      Frequent customer         7.0
43       67      Frequent customer         7.0
44       67      Frequent customer         7.0
45       67      Frequent customer         7.0
46       67      Frequent customer         7.0
47       67      Frequent customer         7.0
48       67      Frequent customer         7.0
49       67      Frequent customer         7.0
50       67      Frequent customer         7.0
51       67      Frequent customer         7.0
52       67      Frequent customer         7.0
53       67      Frequent customer         7.0
54       67      Frequent customer         7.0
55       67      Frequent customer         7.0
56       81  Non-frequent customer        30.0
57       81  Non-frequent customer        30.0
58       82       Regular customer        11.5
59       82       Regular customer        11.5

## 04. Additional Data Cleaning (Outlier Removal)

In [25]:
# checking for prices over 100 / Outlier Search
ords_prods_merge.loc[ords_prods_merge['prices'] > 100]

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,avg_price,spending_flag,order_freq,frequency_flag
10030345,912404,17,12,2,14,5.0,False,21553,5,0,Lowfat 2% Milkfat Cottage Cheese,108,16,14900.0,both,High-range product,Regularly busy,Regularly busy,Most orders,40,Regular customer,108.648299,High Spender,5.0,Frequent customer
10030346,603376,17,22,6,16,4.0,False,21553,3,1,Lowfat 2% Milkfat Cottage Cheese,108,16,14900.0,both,High-range product,Regularly busy,Regularly busy,Most orders,40,Regular customer,108.648299,High Spender,5.0,Frequent customer
10030347,3264360,135,2,2,21,13.0,False,21553,6,0,Lowfat 2% Milkfat Cottage Cheese,108,16,14900.0,both,High-range product,Regularly busy,Regularly busy,Most orders,4,New customer,1154.792308,High Spender,12.0,Regular customer
10030348,892534,135,3,0,8,12.0,False,21553,3,1,Lowfat 2% Milkfat Cottage Cheese,108,16,14900.0,both,High-range product,Busiest day,Busy day,Average orders,4,New customer,1154.792308,High Spender,12.0,Regular customer
10030349,229704,342,8,1,19,30.0,False,21553,9,0,Lowfat 2% Milkfat Cottage Cheese,108,16,14900.0,both,High-range product,Regularly busy,Busy day,Most orders,16,Regular customer,114.426619,High Spender,23.0,Non-frequent customer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29166209,2249946,204099,29,0,8,4.0,False,33664,1,0,2 % Reduced Fat Milk,84,16,99999.0,both,High-range product,Busiest day,Busy day,Average orders,39,Regular customer,1106.743956,High Spender,4.0,Frequent customer
29166210,2363282,204099,31,0,9,2.0,False,33664,1,1,2 % Reduced Fat Milk,84,16,99999.0,both,High-range product,Busiest day,Busy day,Average orders,39,Regular customer,1106.743956,High Spender,4.0,Frequent customer
29166211,3181945,204395,13,3,15,8.0,False,33664,25,0,2 % Reduced Fat Milk,84,16,99999.0,both,High-range product,Regularly busy,Less busy,Most orders,15,Regular customer,451.153540,High Spender,5.0,Frequent customer
29166212,2486215,205227,7,3,20,4.0,False,33664,8,0,2 % Reduced Fat Milk,84,16,99999.0,both,High-range product,Regularly busy,Less busy,Most orders,12,Regular customer,1178.381871,High Spender,12.0,Regular customer
29166213,2232716,205227,10,0,11,4.0,False,33664,23,1,2 % Reduced Fat Milk,84,16,99999.0,both,High-range product,Busiest day,Busy day,Most orders,12,Regular customer,1178.381871,High Spender,12.0,Regular customer

In [24]:
# removing head() restrictions
pd.options.display.max_columns = None

In [26]:
# turning outliers prices into NaNs
ords_prods_merge.loc[ords_prods_merge['prices'] >100, 'prices'] = np.nan

In [27]:
ords_prods_merge['prices'].max()

25.0

### Question 9.
Export your dataframe as a pickle file and store it correctly in your “Prepared Data” folder.

In [28]:
# Exporting dataframe
ords_prods_merge.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'orders_products_grouped.pkl'))